CREATE TABLE IF NOT EXISTS EMPLOYEES
(
    id     INTEGER AUTO_INCREMENT,
    name   VARCHAR(100) NOT NULL,
    dept   VARCHAR(100) NOT NULL,
    salary DOUBLE       NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ROLES
(
    id   INTEGER AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS USERS
(
    id        INTEGER AUTO_INCREMENT,
    username  VARCHAR(100) NOT NULL,
    password  VARCHAR(100) NOT NULL,
    salary    VARCHAR(100) NOT NULL,
    role_id   INTEGER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (role_id) REFERENCES ROLES (name)
);

CREATE TABLE IF NOT EXISTS STREAMERS
(
    id          INTEGER AUTO_INCREMENT,
    tracking_id VARCHAR(100) NOT NULL,
    name        VARCHAR(100) NOT NULL,
    user_id     INTEGER      NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES USERS (id)
);

CREATE TABLE IF NOT EXISTS CLIPS
(
    id          INTEGER AUTO_INCREMENT,
    tracking_id VARCHAR(100) NOT NULL,
    url         VARCHAR(100) NOT NULL,
    user_id     INTEGER      NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES USERS (id)
);